language: rust
rust:
  - stable
  - beta
  - nightly
after_success: |
  [ "$TRAVIS_RUST_VERSION" = stable ] &&
  [ "$TRAVIS_BRANCH" = master ] &&
  [ "$TRAVIS_PULL_REQUEST" = false ] &&
  cargo doc &&
  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
  curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
